#schemaurl: 3bot.person.profile
[info]
#threebot id
tid = ""
#unique id will be 2 max 3 letters 3x[0-9a-z] (unique per topic)
uid = ""
title = "This is the name of a circle"
#enumerator from company, country, city, group, project, funnel, ...
type = ""
tags = ""

[links]
linkedin = ""
websites = []
facebook = ""
telegram = ""

[profile]
intro_video = ""
intro_text_purpose = """
    this is a multi line text
    can be used to describe profile from human perspective
    optional: can be part of the profile.md file
    """
intro_text_experience = """
    optional experience...
    can be part of the profile.md file
    """

