
#schemaurl: 3bot.person.profile
[info]
tid = ""        #threebot id (int) which represents this person
full_name = "Owen Kemp"
#free text for now
countries = ["Austria"]
cities = ["Vienna"]
comment = ""
alias = []
tags = ""
description = """
    
    """
remarks = """
    """

[contactinfo]
email = []
tel = []
telegram = []
skype = []

[address]
city = ""
housenr = ""
postalcode = ""
country = ""

[links]
linkedin = "https://www.linkedin.com/in/aaaaa/"
websites = ["https://www.artichoke-computing.com/#"]
facebook = ""
telegram = ""

[profile]
intro_video = ""
intro_text_purpose = """
    this is a multi line text
    can be used to describe profile from human perspective
    optional: can be part of the profile.md file
    """
intro_text_experience = """
    optional experience...
    can be part of the profile.md file
    """


