#schemaurl: 3bot.person.profile
[info]
#threebot id
tid = ""
#unique name in threebot
name = ""
title = "This is the title of a topic"
#set of aliases
alias = [""]
tags = ""
description = """
    """

[links]
linkedin = ""
websites = []
facebook = ""
telegram = ""

#where is the data of this topic, so all objects can be loaded from filesystem in memory
[git]
url= ""
branch = ""
path = ""  #if not in url

