#schemaurl: 3bot.circle
[info]
#threebot id
tid = ""
#unique name in threebot
name = ""
title = "This is the name of a circle"
#set of aliases
alias = [""]
#enumerator from company, country, city, group, project, ...
type = ""
tags = ""

[links]
linkedin = ""
websites = []
facebook = ""
telegram = ""

[profile]
intro_video = ""
intro_text_purpose = """
    this is a multi line text
    can be used to describe profile from human perspective
    optional: can be part of the profile.md file
    """
intro_text_experience = """
    optional experience...
    can be part of the profile.md file
    """

