#schemaurl: 3bot.site

# represents a site and can include parts from other topics (e.g include markdown from a wiki or a toml data from a data repo)
[info]
#threebot id
tid = ""
#unique name in threebot
name = ""
title = "Title of a site"
#set of aliases
aliases = [""]
tags = ""

[links]
linkedin = ""
websites = []
facebook = ""
telegram = ""

[[includes]]
#"$tid:$circle_id"
topic_ids = ["kristof.3bot:mytopic1"]

    [includes.filter]
    includes = ["kristof.3bot:ourambassadors.vienna"]
    excludes = []



