#schemaurl: 3bot.topic
## can be a wiki or a data repo
[info]
#threebot id
tid = ""
#unique name in threebot
name = ""
title = "This is the title of a topic"
#set of aliases
aliases = [""]
tags = ""

[links]
linkedin = ""
websites = []
facebook = ""
telegram = ""

[git]
url = ""
branch = ""
