# Job, which is executed function which originate 
# from a 3bot
# can be linked to a topic
@url = 3bot.job
id = 0
time_start = 0
time_stop = 0
# defines url of the action to be executed, normally a dot separated url e.g. sal.zos.containers.create
url = "" (S)
# json formatted dict, is always passed as ** to the method key:value,...
params = "" (JSON)
# json formatted dict
result = "" (JSON)
# timeout in seconds
timeout = 300 (I)
# nr of times to retry
retry = 0 (I)
# crystal 3bot id who called it
tbot_id = 0 (I)
# topic id, topic as used in 3bot server for a particular 3bot_id
topic_id = 0 (I)
# return queue, can be any string
return_queue = ""
# secrets, are just strings which need to be given for the person who want to query the return queue
return_queue_secrets = (LS)
# job can be linked to one or more data objects of the 3bot/topic (optional)
datalinks = (LI)